### ISSUE TITLE
serialise example

### ISSUE THREAD

**Issue by brendonparker** [AKST/nuimo-client.js#4]
Your example that prints the serialized output has a typo in the file name.
Suggest change from `serailise.js` to `serialise.js`

**Comment by AKST** [comment]
Hey sorry for whatever reason I never got an email about this, this is like weeks old do you want me to look into this still?

**Comment by AKST** [comment]
On second thought, I've neglected this too much to continue managing it, I might just point this repo to the guy has been doing a good job of managing his fork

**Comment by brendonparker** [comment]
Ha, by weeks, you mean months right? :stuck_out_tongue_winking_eye: 

I haven't played with this library since I submitted the pull request, nor do I really have the time to invest in it. Letting wind-rider take it over seems sensible to me.

**Comment by AKST** [comment]
Haha sweet, yeah they seemed to have done a good job with that. Also lol yes I mean months, I'll have to look into why my email just panned all those emails so this never happens again, like I saw the email for this, so it's strange I never saw all the emails for the issues other's have opened up.
